config/routes.rb
Rails.application.routes.draw do
  # FOREST ADMIN
  mount ForestLiana::Engine => '/forest'

  # FLATS
  resources :flats, only: [:index, :show, :new, :edit, :create, :update] do
    resources :rentals, only: [:index, :show, :new, :edit, :create] do
      member do
        get 'organize_visit', to: 'rentals#organize_visit'
        post 'select_tenant', to: 'rentals#select_tenant'
        post 'confirm_tenant', to: 'rentals#confirm_tenant'
      end
    end
  end

  # TASKS
  resources :tasks, only: [:index, :show, :new, :edit, :create, :update] do
    resources :assignments, only: [ :index, :new, :create, :confirmation ]
  end

  # ASSIGNMENTS
  resources :assignments, only: [ :show, :edit, :update, :destroy ]  do
  	member do
      patch 'valid'
      patch 'reject'
  	end
  end

  # CUSTOM PAGES
  get 'dashboard', to: 'pages#dashboard'
  get 'my-tasks', to: 'tasks#mytasks'
  get 'my_visits', to: 'pages#my_visits'

  #CHATROOM & CONVERSATIONS
  resources :chat_rooms, only: %i[index show create destroy] do
    resources :messages, only: %i[create]
  end
  resources :conversations, only: %i[index show create destroy] do
    resources :direct_messages, only: %i[create update]
  end

  # USERS
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # HOME
  root to: 'pages#home'

end

app/views/layouts/shared/_dashboard-breadcrumb.html.erb
<%# TODO Replace id param with Flutie Gem https://github.com/thoughtbot/flutie %>

<% # VARIABLES
	 # id
	 #	→ string
	 # title
	 #	→ string
	 # links (breadcrumb items)
	 # 	→ [ { text: text, link: link, icon: icon} ]
	 # cta (call to action) - optional
	 # 	→ string
	 # flat - optional
	 # 	→ ActiveRecords @flat

	 # DEFAULT VALUES
	 id = nil if local_assigns[:id].nil?
	 title = nil if local_assigns[:title].nil?
	 links = nil if local_assigns[:links].nil?
	 cta = nil if local_assigns[:cta].nil?
	 flat = nil if local_assigns[:flat].nil?
	 dashboard_text = links.nil? ? ' My dashboard' : ''
%>
<header <%= "id=#{id}" if id %> class="dashboard">
	<div class="container">
		<ul class="breadcrumb">
			<li><%= link_to(raw("<i class=\"fas fa-tachometer-alt\"></i>#{dashboard_text}"), dashboard_path ) %></li>
			<% if links %>
				<% links.each do |item| %>
					<li><%= item[:link] ? raw(link_to(item[:text], item[:link])) : raw(item[:text]) %></li>
				<% end %>
			<% end %>
		</ul>
		<%# TITLE %>
		<h1 class="d-flex justify-content-between align-items-baseline">
			<div><%= raw(title) %></div>
			<% if cta %>
				<div>
					<%= raw(cta) %>
				</div>
			<% end %>
		</h1>
		<%# FLAT INFO (optional) %>
		<% if flat %>
			<p class="d-flex justify-content-between">
				<%= render 'flats/flat-description', flat: flat %>
			</p>
		<% end %>
	</div>
</header>

app/views/layouts/shared/_flat_item_in_menu.html.erb
<li class="list-group-item d-flex justify-content-between" data-flat-id="<%= flat.id %>">
 	<%= short_text(flat.address) %>
 	<div class="actions">
 		<%# TO RENT BUTTON %>
 		<% if flat.pending_rental? %>
 			<%= flat.has_visits? ? raw(badge('visited', '', 'street-view')) : "" %>
 			<% badge_class = flat.num_candidates == 0 ? 'danger' : 'info' %>
 			<%= link_to raw(badge(pluralize(flat.num_candidates, 'candidate'), badge_class, 'users', flat_rental_path(flat, flat.pending_rental_id), false)) %>
 		<% else %>
 			<% badge_class = flat.to_rent ? 'danger' : 'primary' %>
 			<%= link_to raw(badge('New rental', badge_class, 'file-import', new_flat_rental_path(flat.id), false)) %>
 		<% end %>
 		<%# DETAILS BUTTON %>
 		<%#= link_to raw(badge('Flat infos', 'primary', 'building', flat_path(flat.id))) %>
 	</div>
 </li>

app/views/layouts/shared/_flater-bot.html.erb
<% # VARIABLES 
	 bot_action = "If you have any question, <a href=\"#\">just ask</a>." if local_assigns[:bot_action].nil?
%>

<div class="flater-bubble">
	<div id="bubble-message">
		<p>
			<strong class="text-primary">Flater Bot ›</strong> <span id="typed" data-strings="<%= [raw(bot_message)].to_json %>" data-speed="12" data-loop="false"></span>
		</p>
		<% if bot_action %>
			<small class="action"><%= raw(bot_action) %></small>
		<% end %>
	</div>
	<div id="bubble-nav" class="d-flex justify-content-between mt-3">
		<%= link_to '‹ Previous tip', '#', class: 'btn btn-sm btn-outline-primary' %>
		<%= link_to 'Next tip ›', '#', class: 'btn btn-sm btn-outline-primary' %>
	</div>
</div>
<div class="flater-bot"></div>

app/views/layouts/shared/_footer.html.erb
<footer class="page-footer font-small blue">
	<div class="text-center pt-3">
	<small>About us <span class="text-primary">·</span> Our services <span class="text-primary">·</span> We hire! <span class="text-primary">·</span> Contact us <span class="text-primary">·</span> FAQ <span class="text-primary">·</span> Legal notices</small>
	</div>
	<div class="footer-copyright text-center py-3">
		2019 &copy; <strong>Flater</strong> <span class="text-primary">·</span> Select, Rent & Chill!
	</div>
</footer>

app/views/layouts/shared/_modal.html.erb
<%# VARIABLES
id
label
title
content
%>

<div class="modal fade" id="<%= id %>" tabindex="-1" role="dialog" aria-labelledby="<%= label %>" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-<%= id %>" id="<%= id %>"><%= raw(title) %></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<%= raw(content) %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-xl navbar-light">
  <%# LOGO %>
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo_flatter-rvb.png" %>
  <% end %>

  <%# RESPONSIVE MENU BUTTON %>
  <button class="btn navbar-toggler" type="button" data-toggle="canvas" data-target="#bs-canvas-right" aria-expanded="false" aria-controls="bs-canvas-right"><i class="fas fa-bars text-primary"></i></button>
  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> %>

  <%# WIDE SCREEN MENU %>
  <%# TODO Active class for current nav item %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "My dashboard", dashboard_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
        <span class="nav-link nav-logged"><%= link_to "Sign in", new_user_session_path %></span>
        </li>
      <% end %>
      <li class="nav-item">
        <button class="btn" type="button" data-toggle="canvas" data-target="#bs-canvas-right" aria-expanded="false" aria-controls="bs-canvas-right"><i class="fas fa-bars text-primary"></i></button>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/shared/_sidebar.html.erb
<div id="bs-canvas-right" class="bs-canvas bs-canvas-right position-fixed h-100">
	<header class="bs-canvas-header px-3 py-4 overflow-auto">
		<h4>
			<%# USER HEADER %>
			<% if user_signed_in? %>
				<%= image_tag current_user.avatar, class: "avatar", id: "avatar" %>

				<%#= image_tag "https://res.cloudinary.com/dtwpyokni/image/upload/v1558705228/maxime.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
				Hi <%= current_user.first_name %>!
			<%# GUEST HEADER %>
			<% else %>
				You must be logged in
			<% end %>
		</h4>
		<button type="button" class="bs-canvas-close btn close" aria-label="Close" aria-expanded="false">
			<i class="fas fa-reply"></i>
		</button>
	</header>
	<%# USER MENU %>
	<% if user_signed_in? %>
		<h5 class="nav-link text-primary small">Renting</h5>
		<%= link_to raw("<i class=\"fas fa-tachometer-alt\"></i> My dashboard"), dashboard_path, class: "dropdown-item" %>
		<%= link_to raw("<i class=\"fas fa-comments\"></i> My messages <span class=\"badge badge-pill badge-primary\">#{rand(1..10)}</span>"), conversations_path, class: "dropdown-item" %>
		<%= link_to raw("<i class=\"fas fa-building\"></i> My flats <span class=\"badge badge-pill badge-primary\">#{current_user.flats.count}</span>"), flats_path, class: "dropdown-item" %>
		<%= link_to raw("<i class=\"fas fa-file-import\"></i> My applications"), '#', class: "dropdown-item" %>
		<%= link_to raw("<i class=\"fas fa-street-view\"></i> My visits"), my_visits_path, class: "dropdown-item" %>
		<%= link_to raw("<i class=\"fas fa-file-signature\"></i> My contracts"), '#', class: "dropdown-item" %>
		<div class="dropdown-divider"></div>
		<h5 class="nav-link text-primary small">Informations</h5>
		<%= link_to raw("<i class=\"fas fa-user-edit\"></i> Edit my account"), edit_user_registration_path, class: "dropdown-item" %>
		<%= link_to raw("<i class=\"fas fa-bolt text-primary\"></i> Upgrade to Premium Plans"), '#', class: "dropdown-item text-primary" %>
		<div class="dropdown-divider"></div>
		<%= link_to raw("<i class=\"fas fa-sign-out-alt\"></i> Logout"), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
	<%# GUESY MENU %>
	<% else %>
		<div class="dropdown-item"><%= link_to "Sign in with email", new_user_session_path, class: "btn btn-primary btn-block text-left" %></div>
    <%= render "devise/shared/links-sidebar" %>
		<div class="dropdown-divider"></div>
		<div class="dropdown-item"><%= link_to "Create an account", new_user_registration_path, class: "btn btn-sm btn-outline-secondary btn-block text-left" %></div>
	<% end %>
	<%# COMMON MENU %>
	<h5 class="nav-link text-primary small mt-5">About Flater</h5>
	<%= link_to raw("About us"), '#', class: "dropdown-item small" %>
	<%= link_to raw("FAQ"), '#', class: "dropdown-item small" %>
	<%= link_to raw("Contact us"), '#', class: "dropdown-item small" %>
	<%= link_to raw("Legal notices"), '#', class: "dropdown-item small" %>
</div>