config/routes.rb
Rails.application.routes.draw do
  # FOREST ADMIN
  mount ForestLiana::Engine => '/forest'

  # FLATS
  resources :flats, only: [:index, :show, :new, :edit, :create, :update] do
    resources :rentals, only: [:index, :show, :new, :edit, :create] do
      member do
        get 'organize_visit', to: 'rentals#organize_visit'
        post 'select_tenant', to: 'rentals#select_tenant'
        post 'confirm_tenant', to: 'rentals#confirm_tenant'
      end
    end
  end

  # TASKS
  resources :tasks, only: [:index, :show, :new, :edit, :create, :update] do
    resources :assignments, only: [ :index, :new, :create, :confirmation ]
  end

  # ASSIGNMENTS
  resources :assignments, only: [ :show, :edit, :update, :destroy ]  do
  	member do
      patch 'valid'
      patch 'reject'
  	end
  end

  # CUSTOM PAGES
  get 'dashboard', to: 'pages#dashboard'
  get 'my-tasks', to: 'tasks#mytasks'
  get 'my_visits', to: 'pages#my_visits'

  #CHATROOM & CONVERSATIONS
  resources :chat_rooms, only: %i[index show create destroy] do
    resources :messages, only: %i[create]
  end
  resources :conversations, only: %i[index show create destroy] do
    resources :direct_messages, only: %i[create update]
  end

  # USERS
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # HOME
  root to: 'pages#home'

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :rental
  has_many :assignments, dependent: :destroy
  
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  ACTIONS = ['visit', 'cleaning', 'check-in or out']
  STATUS = ['to do', 'in progress', 'done']
  FACE_IDS = ['01', '02', '03', '04']

  scope :done, -> { where(status: "2") }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:mytasks, :show, :destroy]

  def index
    @tasks = Task.where(status: 0)
  end

  def show
    @marker =
      {
        lat: @task.latitude,
        lng: @task.longitude
      }
  end

  def mytasks
    # My tasks (as owner)
    @all_tasks = current_user.tasks.order('status ASC, id ASC')
    @tasks_to_assign = @all_tasks.where('tasks.id NOT IN (SELECT task_id FROM assignments a WHERE a.validated = TRUE)')
    @tasks_in_progress = @all_tasks.joins(:assignments).where(assignments: { validated: true }, status: 0..1).uniq
    @tasks_done = @all_tasks.joins(:assignments).where(assignments: { validated: true }, status: '2').uniq

    ### DEBUG
    # p @all_tasks.ids
    # p @tasks_to_assign.map(&:id)
    # p @tasks_in_progress.map(&:id)
    # p @tasks_done.map(&:id)
    # p @all_tasks.ids - @tasks_to_assign.map(&:id) - @tasks_in_progress.map(&:id) -@tasks_done.map(&:id)

    # My assignments (as concierge)
    @tasks_validated = current_user.tasks_validated
    @tasks_applied = current_user.tasks_applied
    # @tasks_applied = @my_assignments.where(validated: false)
    # TOUTES LES TACHES AUXQUELLES J'AI POSTULÉES QUI SONT VALIDÉES PAR UN AUTRE USER_ID
    @tasks_missed = current_user.tasks_missed
    # @tasks_missed = @assignments.where(task: @tasks_applied, validated: true).where.not(user: current_user)
    # @tasks_missed = @assignments.where(id: @my_assignments.id, validated: true).where_not(user_id: current_user)
    # @tasks_missed = @assignments.where(validated: true).where_not(user_id: current_user)
    # @tasks_missed = @assignments.where(user_id: current_user).where(validated: true)

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @participants = @task.rental.dossiers.where(status: "ok_for_visit")
    respond_to do |format|
      if @task.save!
        format.html { redirect_to my_visits_path"?new", notice: 'Visit was successfully created.' }
        @participants.update(status: "visiting")
        # format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        # format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to @task
  end

  def destroy
  end

  private

  def set_task
    # All tasks
    @tasks = Task.all
    @assignments = Assignment.all
    # User tasks
    if current_user
      @my_tasks = Task.where(user_id: current_user)
      # @my_assignments = Assignment.where(user_id: current_user)
      @my_assignments = current_user.owned_tasks
    end
    # Task details
    if params[:id]
      @task = Task.find(params[:id])
    end
  end

  def task_params
    params.require(:task).permit(:action, :status, :location, :price, :date, :user_id, :rental_id)
  end
end

app/views/tasks/_mytasks-header-menu.html.erb
<%# VARIABLES
title
links : text, title, path, color, count, data

# TWEAKS TO IMPLEMENT
- tooltip : data-toggle="tooltip" data-html="true" title="<em>Tooltip</em> <u>with</u> <b>HTML</b>"
%>

<div id="menu" class="d-flex justify-content-between">
	<h2 class="subtitle"><strong><%= title.capitalize %></strong></h2>
	<div class="menu">
		<% links.each do |link| %>
			<%= link_to raw("#{link[:text]} <span class=\"badge badge-pill badge-#{link[:color]}\">#{link[:count]}</span>"), link[:path], class: 'btn', data: link[:data], title: link[:title] %>
		<% end %>
	</div>
</div>

app/views/tasks/_mytasks-list.html.erb
<%# VARIABLES
query
%>

<ul id="tasks-list" class="list-group">
	<li class="list-headers d-flex justify-content-between">
		<div class="task-id">#ID</div>
		<div class="task-action">ACTIONS</div>
		<div class="task-date"><i class="far fa-calendar-alt"></i> DATE</div>
		<div class="task-location"><i class="fas fa-map-marker-alt"></i> LOCATION</div>
		<div class="task-applicants">APPLICANTS</div>
		<div class="task-status">STATUS</div>
		<div class="task-tips">TIPS €</div>
	</li>
	<% query.each do |task| %>
	<% status = Task::STATUS[task.status.to_i] %>
	<% case task.status
		when "0"
			status_class = 'danger'
			applicant_class = 'dark'
		when "1"
			status_class = 'warning'
			applicant_class = 'dark'
		when "2"
			status_class = 'success'
			applicant_class = 'success'
		else 
			status_class = 'dark'
			applicant_class = 'dark'
		end
	%>
	<li class="list-group-item">
		<a href="/tasks/<%= task.id %>" class="d-flex justify-content-between py-2">
			<%# TASK ID, ACTION, DATE, LOCATION %>
			<div class="task-id">#<%= task.id %></div>
			<div class="task-action"><%= task.action.capitalize %></div>
			<div class="task-date"><%= task.date %></div>
			<div class="task-location"><i class="fas fa-map-marker-alt text-muted"></i> <%= task.location %></div>
			<%# TASK APPLICANT %>
			<div class="task-applicants">
				<% if params[:role] == 'concierge' && params[:assigned] == '1' %>
					<i class="fas fa-check-circle text-<%= applicant_class %>"></i>
				<% else %>
					<% applicants = Assignment.where(task_id: task.id) %>
					<% applicant_class = (applicants.count > 0) ? 'dark' : 'danger' %>
					<i class="fas fa-users text-muted"></i> <span class="badge badge-pill badge-<%= applicant_class %>"><%= applicants.count %></span>
				<% end %>
			</div>
			<div class="task-status"><span class="badge badge-pill badge-<%= status_class %>"><%= status.capitalize if status %></span></div>
			<div class="task-tips"><%= task.price %>€</div>
		</a>
	</li>
	<% end %>
</ul>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class="container">
	<br>
	
	<% if current_user.id == @task.user_id %>
		<h1>Edit task <%= @task.id %> (you are the owner)</h1>
	
	  <div class="container">
	  	<%= simple_form_for (@task) do |f| %>
	  	<%= f.error_notification %>
	  	<%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
	  	<%= f.input :status, :as => :hidden, :input_html => { :value => 0 } %>
	  	<%= f.input :action, selected:'Visit', collection: Task::ACTIONS %>
	  	<%= f.input :location %>
	  	<%= f.input :date %>
	  	<%= f.input :price %>
	  	<%= f.button :submit, class: "btn-primary" %>
	  	<%= link_to "‹ Back", my_tasks_path , {:class=>"btn btn-default"} %>
	  	<% end %>
	  </div>
	<% else %>
		<h1>You cannot edit this task! Only the task owner can!</h1>
	<% end %>



</div>

app/views/tasks/index.html.erb
<div class="container">
	
	<br>
	<h1>You can currently apply for <strong><%= @tasks.count %> tasks</strong> near <i class="fas fa-map-marker-alt"></i> <strong>Lyon</strong></h1>
	
	<div class="tasks-grid">
		<% @tasks.each do |task| %>
			<div class="task-card show-one">
			  <%= cl_image_tag("Pics/#{task.action}",
          width: 400, height: 300, crop: :fill, :effect=>"grayscale") %>
			  <div class="task-card-infos">
			    <div class="task-card-description">
			      <h2><%= task.action.capitalize %></h2>
			      <p><strong>Status: </strong><%= Task::STATUS[task.status.to_i].capitalize %></p>
			      <p><strong>Location: </strong><%= task.location %></p>
			      <p><strong>Date: </strong><%= task.date %></p>
			      <p><strong>Flat owner: </strong><%= task.user_id %></p>
			    </div>
			    <h2 class="task-card-pricing"><%= task.price %> €</h2><!-- 
			    <img src='https://kitt.lewagon.com/placeholder/users/krokrob' class="task-card-user avatar-bordered"/>
 -->
				<%= cl_image_tag("Faces/face#{rand(1..12)}",
				:transformation=>[{ :gravity=>"face", :radius=>"max", :crop=>"crop"}, {:width=>200, :crop=>"scale"}], :class => "task-card-user avatar-bordered") %>
			  </div>
			  <div class="d-flex m-1 justify-content-between">
				  <%= link_to "Details", task_path(task), class: 'btn btn-secondary mr-1' %>
				  <% if current_user.id == task.user_id %>
				  <%= link_to "Edit" , edit_task_path(task), class: 'btn btn-primary' %>
				  <% end %>
				  <%= link_to "Apply" , new_task_assignment_path(task), class: 'btn btn-info' %>
			  </div>
			</div>
		<% end %>
	</div>

</div>

app/views/tasks/mytasks.html.erb
<div class="container">
	<% # TITLES
	owner = { title: "as owner", count: @tasks_to_assign.count + @tasks_in_progress.count }
	concierge = { title: "as concierge", count: @my_assignments.count }
	%>

	<%# HEADER %>
	<header class="d-flex justify-content-between py-3">
		<h1 class="title">My Tasks</h1>
		<div id="user-menu">
			<i class="fas fa-eye"></i>
			<%= link_to raw("#{owner[:title].capitalize} <span class=\"badge badge-pill badge-warning\">#{owner[:count]}</span>"), my_tasks_path(role: 'owner'), class: 'btn' %>
			<%= link_to raw("#{concierge[:title].capitalize} <span class=\"badge badge-pill badge-warning\">#{concierge[:count]}</span>"), my_tasks_path(role: 'concierge'), class: 'btn' %>
			<%= link_to '+ Create a task', new_task_path, class: 'btn btn-primary' %>
		</div>
	</header>

	<%# OWNER TASKS %>
	<% if !params[:role] || params[:role] == 'owner' %>
		<%# OWNER MENU %>
		<%= render 'mytasks-header-menu',
				title: owner[:title],
				links: [
					{ text: 'Not assigned', path: '?validated=0', color: 'danger', count: @tasks_to_assign.count },
					{ text: 'To start / In progress', path: '?validated=1', color: 'warning', count: @tasks_in_progress.count },
					{ text: 'Done', path: '?validated=1&status=2', color: 'success', count: @tasks_done.count },
					{ text: 'All', path: my_tasks_path(task: 'all'), color: 'dark', count: @all_tasks.count }
				]
		%>
		<%# TASKS QUERIES %>
		<% if params[:validated] == "0"
				owner_query = @tasks_to_assign
			 elsif params[:validated] == "1" && params[:status] == "2"
				owner_query = @tasks_done
			 elsif params[:validated] == "1"
				owner_query = @tasks_in_progress
			 elsif params[:task] == 'all'
				owner_query = @all_tasks
			 else
			 	owner_query = @tasks_to_assign # By default, not assigned tasks are displayed
			 end
		%>
		<%# TASKS LIST %>
		<%= render 'mytasks-list', query: owner_query %>
		<%#= raw(ap owner_query) %>
	<% end %>

	<%# CONCIERGE TASKS %>
	<% if params[:role] == 'concierge' %>
		<%# CONCIERGE MENU %>
		<%= render 'mytasks-header-menu',
				title: concierge[:title],
				links: [
					{ text: 'Assigned', path: my_tasks_path(role: params[:role], assigned: 1), color: 'success', count: @tasks_validated.count, data: { toggle: 'tooltip', html: true}, title: 'All my tasks where I am assigned as a concierge' },
					{ text: 'Not assigned yet', path: my_tasks_path(role: params[:role], assigned: 0, status: 0), color: 'warning', count: @tasks_applied.count, data: { toggle: 'tooltip', html: true}, title: 'All tasks I have applied as a concierge' },
					{ text: 'Missed', path: my_tasks_path(role: params[:role], assigned: 0, status: 1), color: 'danger', count: @tasks_missed.count, data: { toggle: 'tooltip', html: true}, title: 'All tasks I missed as a concierge' },
					{ text: 'All', path: my_tasks_path(role: params[:role]), color: 'dark', count: (@tasks_validated.count + @tasks_applied.count + @tasks_missed.count), data: { toggle: 'tooltip', html: true}, title: 'All my tasks as a concierge' }
				]
		%>
		<%# TASKS QUERIES %>
		<% if params[:assigned] == "1"
				test = 'AAA'
				concierge_query = @tasks_validated
			 elsif params[:assigned] == "0" && params[:status] == "0"
				test = 'BBB'
				concierge_query = @tasks_applied
			 elsif params[:assigned] == "0" && params[:status] == "1"
				test = 'CCC'
				concierge_query = @tasks_missed
			 elsif params[:assignment] == 'all'
				test = 'DDD'
				concierge_query = @my_assignments
			 else
				test = 'EEE'
			 	concierge_query = @tasks_validated # By default, not assigned tasks are displayed
			 end
		%>
		<%# VIEW TASKS %>
		<%= render 'mytasks-list', query: concierge_query %>
		<%#= raw(ap test) %>
		<%#= raw(ap concierge_query) %>
	<% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
	<h1>New task (from flat owner):</h1>

	<%= simple_form_for (@task) do |f| %>
	<%= f.error_notification %>
	<%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
	<%= f.input :status, :as => :hidden, :input_html => { :value => 0 } %>
	<%= f.input :action, selected:'Visit', collection: Task::ACTIONS %>
	<%= f.input :location %>
	<%= f.input :date, as: :date, html5:true,:input_html => { :value => Date.today, class: "datepicker"} %>
	<%= f.input :price %>
	<%= f.button :submit, class: "btn-primary" %>
	<%= link_to "‹ Back", my_tasks_path , {:class=>"btn btn-default"} %>
	<% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
	<header class="d-flex justify-content-between pt-3">
		<h1 class="title d-flex justify-content-between">
      #<%= @task.id %> <%= @task.action.capitalize %>
      <%# # DON'T DISPLAY THIS PART %>
      <% if false %>
        <%# TASK STATUS %>
        <%# FLAT OWNER %>
        </strong><%= @task.user_id %> / <%= current_user.id %>
      <% end %>
    </h1>
    <%# ACTIONS %>
		<div id="user-menu">
      <strong class="px-5" style="font-size: 1.5rem;"><%= @task.price %> €</strong>
      <%= link_to "Apply for it" , new_task_assignment_path(@task), class: 'btn btn-info' %>
      <%= link_to raw('<i class="fas fa-pen"></i> Edit') , edit_task_path(@task), class: 'btn btn-sm' if current_user.id == @task.user_id %>
		</div>
	</header>

  <%# TASK DETAILS %>
  <ul class="lead text-muted d-flex justify-content-between pb-3">
    <li><i class="fas fa-map-marker-alt"></i> <%= @task.location %></li>
    <% status = Task::STATUS[@task.status.to_i] %>
    <li><%= status.capitalize %> on <i class="far fa-calendar-alt"></i> <%= @task.date %></li>
    <li><i></i>  <%= link_to "#{pluralize(@task.rental.dossiers.where(status: "visiting").count, 'candidate')} invited" ,  flat_rental_path(@task.rental.flat, @task.rental) if @task.rental.nil? == false %> </li>
    <li><i class="fas fa-users"></i> <%= pluralize(@task.assignments.count, 'applicant') %> (as concierge)</li>
  </ul>
</div>

<%# MAPBOX %>
<div id="map" style="width: 100%; height: 60vh;" data-marker="<%= @marker.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>


<%# APPLICANTS LIST %>
<% if @task.assignments.count > 0 && @task.user_id == current_user.id %>
  <div id="applicants-list" class="container">
    <h2><%= pluralize(@task.assignments.count, 'applicant') %></h2>
    <% @task.assignments.each do |assignment| %> 
      <%= render 'assignments/applicant-card', assignment: assignment %>
    <% end %>
  </div>
<% end %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>