config/routes.rb
Rails.application.routes.draw do
  # FOREST ADMIN
  mount ForestLiana::Engine => '/forest'

  # FLATS
  resources :flats, only: [:index, :show, :new, :edit, :create, :update] do
    resources :rentals, only: [:index, :show, :new, :edit, :create] do
      member do
        get 'organize_visit', to: 'rentals#organize_visit'
        post 'select_tenant', to: 'rentals#select_tenant'
        post 'confirm_tenant', to: 'rentals#confirm_tenant'
      end
    end
  end

  # TASKS
  resources :tasks, only: [:index, :show, :new, :edit, :create, :update] do
    resources :assignments, only: [ :index, :new, :create, :confirmation ]
  end

  # ASSIGNMENTS
  resources :assignments, only: [ :show, :edit, :update, :destroy ]  do
  	member do
      patch 'valid'
      patch 'reject'
  	end
  end

  # CUSTOM PAGES
  get 'dashboard', to: 'pages#dashboard'
  get 'my-tasks', to: 'tasks#mytasks'
  get 'my_visits', to: 'pages#my_visits'

  #CHATROOM & CONVERSATIONS
  resources :chat_rooms, only: %i[index show create destroy] do
    resources :messages, only: %i[create]
  end
  resources :conversations, only: %i[index show create destroy] do
    resources :direct_messages, only: %i[create update]
  end

  # USERS
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # HOME
  root to: 'pages#home'

end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  has_many :rentals, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def num_candidates
    self.rentals.where(pending: true).first.dossiers.count
  end

  def has_visits?
    self.rentals.where(pending: true).first.tasks.exists?(action: "Visit")
  end

  def pending_rental?
    self.rentals.exists?(pending: true)
  end

  def pending_rental
     self.rentals.where(pending: true)
  end

  def pending_rental_id
    self.rentals.where(pending: true).first.id
  end

  def initial_rent
    return nil unless rentals.any?
    return rentals.find_by(pending: true).initial_rent if pending_rental?

    rentals.order(start_date: :desc).first.initial_rent
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.where(owner_id: current_user)
    @markers = @flats.map do |flat|
      {
        id: flat.id,
        lat: flat.latitude,
        lng: flat.longitude,
        infoWindow: render_to_string(partial: "flats/infowindow", locals: { flat: flat }),
        image_url: helpers.asset_url('ico_location.svg')
      }
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @marker = [{
      id: @flat.id,
      lat: @flat.latitude,
      lng: @flat.longitude,
      infoWindow: render_to_string(partial: "flats/infowindow", locals: { flat: @flat }),
      image_url: helpers.asset_url('ico_location.svg')
    }]
  end
end

app/views/flats/_flat-description.html.erb
<% 
flat_description = [
	{ id: 'address', data: flat.address, icon: 'map-marker-alt' },
	{ id: 'rooms', data: pluralize(flat.nb_rooms, 'room'), icon: 'bed' },
	{ id: 'surface', data: "#{flat.surface.to_i} m<sup>2</sup>", icon: 'vector-square' },
	{ id: 'furniture', data: flat.furnished ? "Furnished"  : "Not furnished", icon: 'couch' },
	{ id: 'rent', data: "#{number_with_precision(flat.initial_rent, precision: 2)}€<span class=\"small text-muted\"> / month</span>", icon: 'hand-holding-usd' },
]
%>

<% flat_description.each do |detail| %>
	<span id="flat-<%= detail[:id] %>"><i class="fas fa-<%= detail[:icon] %> text-primary"></i> <%= raw(detail[:data]) %></span>
<% end %>

app/views/flats/_flat_item_in_menu.html.erb
<li class="list-group-item d-flex justify-content-between" data-flat-id="<%= flat.id %>">
	<%= short_text(flat.address) %>
	<div class="actions">
		<%# TO RENT BUTTON %>
		<% if flat.pending_rental? %>
			<%= flat.has_visits? ? raw(badge('visited', '', 'street-view')) : "" %>
			<% badge_class = flat.num_candidates == 0 ? 'danger' : 'info' %>
			<%= link_to raw(badge(pluralize(flat.num_candidates, 'candidate'), badge_class, 'users', flat_rental_path(flat, flat.pending_rental_id), false)) %>
		<% else %>
			<% badge = flat.to_rent ? { text: 'New rental', color: 'danger', icon: 'file-import', hide: false } : { text: 'New rental?', color: 'primary', icon: 'user', hide: true } %>
			<%= link_to raw(badge(badge[:text], badge[:color], badge[:icon], new_flat_rental_path(flat.id), badge[:hide])) %>
		<% end %>
		<%# DETAILS BUTTON %>
		<%#= link_to raw(badge('Flat infos', 'primary', 'building', flat_path(flat.id))) %>
	</div>
</li>

app/views/flats/_infowindow.html.erb
<div class="bubble-flat">
	<div class="flat-img" style="background-image: url(<%= image_path "flats/flat#{rand(1..18)}.jpg" %>)">
		<%= raw(badge('Details', 'light', 'eye', flat_path(flat.id))) %>
	</div>
	<div class="flat-info">
		<%# TODO Add context to implement short_text(flat.address, 24) %>
		<%= render 'flats/flat-description', flat: flat %>
	</div>
</div>

app/views/flats/index.html.erb
<div class="flat-container">
	<div class="card-flats">
		<h1>
			<i class="fas fa-map-marker-alt small"></i> <strong>Lyon</strong>
			<span class="badge badge-pill badge-primary"><%= current_user.flats.count %></span>
		</h1>

		<ul id="flats-map" class="list-group list-group-flush">
			<li class="list-group-item">
				<i class="fas fa-building text-muted"></i> <strong>My flats to rent</strong>
			</li>
			<% @flats.each do |flat| %>
				<% if flat.to_rent == true %>
					<%= render 'flat_item_in_menu',
							flat: flat %>
				<% end %> 
			<% end %>
			<li class="list-group-item">
			<i class="fas fa-building text-muted"></i> <strong>My other flats</strong></li>
			<% @flats.each do |flat| %>
				<% if flat.to_rent == false %>
					<%= render 'flat_item_in_menu',
							flat: flat %>
				<% end %> 
			<% end %>
		</ul>
	</div>

	<%# MAPBOX %>
	<div id="map" style="width: 100%; height: 100vh;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
	</div>
</div>

app/views/flats/show.html.erb
<%# HEADER %>
<%= render 'layouts/shared/dashboard-breadcrumb',
		id: "flat-details",
		title: "Flat details <small class=\"text-muted\">##{@flat.id}</small>",
		links: [
			{ text: "My flats", link: flats_path },
			{ text: "Flat ##{@flat.id}" }
		],
		cta: "#{link_to 'Edit', edit_flat_path, class: 'btn btn-outline-secondary'} #{link_to 'New rental', new_flat_rental_path(@flat), class: 'btn btn-primary'}",
		flat: @flat
%>

<div id="flat-details" class="container">
	<div class="row">
		<%# MAP %>
		<div class="col col-sm-12 col-lg-6">
			<div id="map" style="width: 100%; height: 540px;" data-markers="<%= @marker.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
		</div>
		<%# RENTAL %>
		<div class="col col-sm-12 col-lg-6">
			<h2>Rental history</h2>
			<% @flat.rentals.order(:start_date).reverse.each do |rental| %>
				<div class="card-dashboard">
					<div class="card-content no-gutters">
						<div class="d-flex justify-content-between">
							<h3><%= link_to "Rental ref. #F#{@flat.id}R#{rental.id}" , flat_rental_path(@flat, rental), class: 'text-secondary'%></h3>
							<%= raw(badge(rental.status[:text], rental.status[:color], rental.status[:icon], flat_rental_path(@flat, rental.id), false)) %>
						</div>
						<div class="row py-3">
							<%# RENTAL IS PENDING %>
							<% if rental.pending %>
								<div class="col-5">
									<i class="fas fa-users text-primary"></i> <strong><%= pluralize(rental.dossiers.count, 'candidate') %></strong>
								</div>
								<div class="col-7">
									<% rental.dossiers.each do |dossier| %>
										<%= cl_image_tag("Faces/#{dossier.candidate.facebook_picture_url}", width: 475, height: 300, crop: :fit, class: 'avatar-small') %>
									<% end %>
								</div>
							<%# RENTAL IS CLOSED %>
							<% else %>
									<div class="col-4">
										<i class="fas fa-user text-primary"></i> <small class="text-muted">tenant</small><br/>
									</div>
									<div class="col-8">
										<%= cl_image_tag("Faces/#{User.find(rental.tenant_id).facebook_picture_url}",
									:transformation=>[{ :gravity=>"face", :radius=>"max", :crop=>"crop"}, {:width=>'200', :crop=>"scale"}], :class => "avatar mr-3") %>
										<strong><%= "#{User.find(rental.tenant_id).first_name} #{User.find(rental.tenant_id).last_name}" %></strong>
									</div>
							<% end %>
						</div>
						<%# RENTAL DETAILS %>
						<div class="col-12 py-1">
							<i class="fas fa-hand-holding-usd text-primary"></i> <strong><%= number_with_precision(rental.initial_rent, precision: 2) %>€</strong> <small class="text-muted">/ month</small>
						</div>
						<div class="row py-1">
							<div class="col-6">
								<i class="fas fa-calendar-alt text-primary"></i> <small class="text-muted">start date</small> <strong><%= rental.start_date %></strong>
							</div>
							<div class="col-6">
								<i class="fas fa-calendar-alt text-primary"></i> <small class="text-muted">end date</small> <strong><%= rental.end_date ? rental.end_date : 'undefined' %></strong>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>