config/routes.rb
Rails.application.routes.draw do
  # FOREST ADMIN
  mount ForestLiana::Engine => '/forest'

  # FLATS
  resources :flats, only: [:index, :show, :new, :edit, :create, :update] do
    resources :rentals, only: [:index, :show, :new, :edit, :create] do
      member do
        get 'organize_visit', to: 'rentals#organize_visit'
        post 'select_tenant', to: 'rentals#select_tenant'
        post 'confirm_tenant', to: 'rentals#confirm_tenant'
      end
    end
  end

  # TASKS
  resources :tasks, only: [:index, :show, :new, :edit, :create, :update] do
    resources :assignments, only: [ :index, :new, :create, :confirmation ]
  end

  # ASSIGNMENTS
  resources :assignments, only: [ :show, :edit, :update, :destroy ]  do
  	member do
      patch 'valid'
      patch 'reject'
  	end
  end

  # CUSTOM PAGES
  get 'dashboard', to: 'pages#dashboard'
  get 'my-tasks', to: 'tasks#mytasks'
  get 'my_visits', to: 'pages#my_visits'

  #CHATROOM & CONVERSATIONS
  resources :chat_rooms, only: %i[index show create destroy] do
    resources :messages, only: %i[create]
  end
  resources :conversations, only: %i[index show create destroy] do
    resources :direct_messages, only: %i[create update]
  end

  # USERS
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # HOME
  root to: 'pages#home'

end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :flat
  has_one :tenant, class_name: "User", foreign_key: "tenant_id"
  has_many :dossiers, dependent: :destroy
  has_many :tasks, dependent: :destroy

  def pending?
    pending == true
  end

  def status
    if self.pending
      { text: "pending", icon: "clock", color: "warning" }
    elsif self.start_date >= Date.today
      { text: "future rental", icon: "check", color: "info" }
    elsif self.end_date.nil? == false && self.end_date < Date.today
      { text: "previous rental", icon: "check", color: "secondary" }
    else
      { text: "current rental", icon: "check", color: "primary" }
    end
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_flat, only: [:new, :create]

  def show
    @rental = Rental.find(params[:id])
    @flat = Flat.find(params[:flat_id])
  end

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.pending = true
    @rental.flat = @flat
    @rental.save!
    @flat = Flat.find(@rental.flat.id)
    @flat.update!(to_rent: true)
    # OPTIMIZE IF OK ... else ...
  end

	def organize_visit
	  @rental = Rental.find(params[:id])
	  @flat = Flat.find(params[:flat_id])
	  @task = Task.new
	  @invited_participants = @rental.dossiers.where(status: "ok_for_visit")
	end

  def select_tenant
    @rental = Rental.find(params[:id])
    @flat = Flat.find(params[:flat_id])
    @selected_dossier = Dossier.find(params[:dossier_id])
  end

  def confirm_tenant
    @rental = Rental.find(params[:id])
    @flat = Flat.find(params[:flat_id])
    @selected_dossier = Dossier.find(params[:dossier_id])
    respond_to do |format|
      if @rental.update!(pending: false, tenant_id:@selected_dossier.candidate.id)
        format.html { redirect_to flats_path, notice: 'Rental was successfully updated.' }
        @flat.update!(to_rent: false)
        # format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        # format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def rental_params
    params.require(:rental).permit(:description, :start_date, :end_date, :initial_rent)
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

end

app/views/rentals/_candidates_list.html.erb
<% rental.dossiers.each do |dossier| %>
	<% if dossier.status == status %>
		<% candidate = User.find(dossier.candidate_id) %>
		<%# TODO Debug init_flat_selector %>
		<li class="list-group-item d-flex justify-content-between align-items-center">
			<div class="w-100">
				<h4 class="d-flex align-items-center">
					<%# USER AVATAR %>
					<%= cl_image_tag("Faces/#{candidate.facebook_picture_url}",
					:transformation=>[{ :gravity=>"face", :radius=>"max", :crop=>"crop"}, {:width=>'200', :crop=>"scale"}], :class => "avatar avatar-large mr-3"
					) %>
					<div class="w-100">
						<%# USER FULLNAME %>
						<div class="dossier-details d-flex align-items-center">
							<span class="mr-2"><%= "#{candidate.first_name.capitalize}" %> <%= "#{candidate.last_name.upcase}" %></span>
						</div>
						<%# CHAT MESSAGING %>
						<div>
              <% @conversation = Conversation.get(candidate.id, current_user.id) %>
              <% if @conversation %>
							  <% messages_count = @conversation.direct_messages.where(user: @conversation.opposed_user(current_user)).where(read: false).count %>
              <% else %>
                <% messages_count = 0 %>
              <% end %>
							<% message_class = 'info' if status == 'visiting' %>
							<% message_class = 'primary' if status == 'ok_for_visit' %>
							<% message_class = 'warning' if status == 'to_improve' %>
							<% message_class = 'danger' if status == 'not_selected' %>
							<% messages_display = messages_count > 0 ? false : true %>
							<% messages_new = messages_count > 0 ? 'new message' : '' %>
							<span class="mr-2">
                <%= raw(badge(messages_count, message_class, 'comments', conversations_path(user_id: candidate), messages_display,  methode: 'post')) %></span>
							<strong class="new-message"><%= messages_new %></strong>
						</div>
					</div>
					<%# BUTTONS %>
					<div class="drag-and-drop">
						<% if dossier.status == "visiting" %>
							<%= link_to "Select", select_tenant_flat_rental_path(@flat, @rental, dossier_id: dossier.id), method: :post, class: 'btn btn-info' %>
						<% end %>
						<% if dossier.status == "ok_for_visit" %>
							<%#= "[BOUTON Don't select]" %>
							<i class="fas fa-arrows-alt"></i>
						<% end %>
						<% if dossier.status == "to_improve" || dossier.status == "not_selected"%>
							<%#= "[BOUTON Ok for visits]" %>
							<i class="fas fa-arrows-alt"></i>
						<% end %>
					</div>
				</h4>
				<%# DOCUMENTS %>
				<div id="candidate-documents" class="d-flex justify-content-between align-items-center">
					<strong><i class="fas fa-file-invoice-dollar text-primary"></i> <%= "#{dossier.monthly_revenues}" %>€ / month</strong>
					<%
					documents.each do |document|
						if status == 'visiting' || status == 'ok_for_visit'
							document_ok = "<i class=\"fas fa-check text-primary\"></i>"
						else
							document_ok = ["<i class=\"fas fa-check text-primary\"></i>", "<i class=\"fas fa-times text-danger\"></i>"].sample
						end
						%>
						<a data-toggle="modal" data-target="#document-<%= document %>"><%= raw("#{document.gsub('-', ' ').capitalize} #{document_ok}") %></a>
					<% end %>
				</div>
			</div>
		</li>
	<% end %>
<% end %>

app/views/rentals/create.html.erb
<%# HEADER %>
<%= render 'layouts/shared/dashboard-breadcrumb',
		title: "Rental created <i class=\"fas fa-check text-primary\"></i>",
		links: [
			{ text: "My flat ##{@flat.id}", link: flat_path(@flat.id) },
			{ text: "Rental ##{@rental.id} (created)" }
		],
		flat: @flat
%>

<div class="container">
	<%# CREATE A NEW RENTAL %>
	<div class="row">
		<div class="col col-sm-12 col-lg-8">
			<%# 1. FLATER RENTAL LINK %>
			<p class="lead"><strong>1. Share link </strong></p>
			<div class="input-group mb-3">
				<div class="input-group-prepend align-items-center">
					<span class="input-group-text fas fa-link"></span>
				</div>
				<input class="inputCopy form-control" value="<%= "https://submit.flater.app/f#{@flat.id}r#{@rental.id}" %>" />
				<%# link: www.flater.co/flats/#{@flat.id}/rentals/#{@rental.id}/dossier/new %>
        <div class="input-group-append">
          <button class="btn btn-primary btn-copy">Copy</button>
        </div>
			</div>

			<%# 2. FLATER RENTAL REFERENCES %>
			<p>2. Or send flater reference</strong> <!-- after login <a href="#">in application page</a>: --></p>
			<div class="input-group mb-3">
				<div class="input-group-prepend align-items-center">
					<span class="input-group-text fas fa-folder-open"></span>
				</div>
				<input class="inputCopy form-control" value="#F<%= @flat.id%>R<%=@rental.id%>" />
         <div class="input-group-append">
          <button class="btn btn-secondary btn-copy">Copy</button>
        </div>
			</div>

			<%# 3. FLATER RENTAL EMAIL %>
			<p>3. Or use this flater email <!--  so notifications and applications are pushed in <%= link_to 'your dashboard', dashboard_path %>: --></p>
			<div class="input-group mb-3">
				<div class="input-group-prepend align-items-center">
					<span class="input-group-text far fa-envelope"></span>
				</div>
				<input class="inputCopy form-control" value="F<%= @flat.id%>R<%=@rental.id%>@flater.app" />
			 <div class="input-group-append">
          <button class="btn btn-secondary btn-copy">Copy</button>
        </div>
      </div>
      <br>
      <br>
			<%= link_to "Back to my flats", flats_path , {:class=>"btn btn-secondary"} %>
		</div>
		<%# FLATER BOT %>
		<div class="col col-sm-12 col-lg-4">
			<%= render 'layouts/shared/flater-bot',
					bot_message: "Well done! I hope you will receive dozen and dozen of applications! <strong>Don't worry, I will preselect the best one for you!</strong>"
			%>
		</div>
	</div>
</div>

app/views/rentals/new.html.erb
<% # VARIABLES
	 bonus = @flat.furnished ? 1.20 : 1
	 min_rent = 13 ####  €/m2 - basis
	 max_rent = 16 ####  €/m2 - basis
	 min_rent = @flat.surface * min_rent * bonus
	 max_rent = @flat.surface * max_rent * bonus
%>

<%# HEADER %>
<%= render 'layouts/shared/dashboard-breadcrumb',
		id: 'create-rental',
		title: 'Create a new rental',
		links: [
			{ text: "My flat ##{@flat.id}", link: flat_path(@flat.id) },
			{ text: "Create a new rental" }
		],
		cta: "#{link_to 'History', flat_path(@flat.id), class: 'btn btn-outline-secondary'}",
		flat: @flat
%>

<div class="container">
	<%# CREATE A NEW RENTAL %>
	<div class="row">
		<div class="col col-sm-12 col-lg-8">
			<%= simple_form_for([@flat, @rental]) do |f| %>
		  <div class="form-inputs">
				<%= f.input :description, label: "Complementary information", input_html: { value: @flat.description } %>
		    <%= f.input :start_date, as: :date, html5:true, input_html: { :value => Date.today, class: "datepicker"} %>
		    <%= f.input :initial_rent, label: "Initial rent (€ / month, excl. charges)", input_html: { value: min_rent.to_i } %>
		    <small class="form-text text-muted"><%=  "Previous rental was #{number_with_precision(@flat.initial_rent, precision: 2)}€ / month"%></small>
		    <br> <br>
		    <%= f.button :submit, class: "btn btn-primary" %>
      	<%= link_to "‹ Back", :back, class: 'btn btn-secondary' %>
		  </div>
		<% end %>
		</div>
		<%# FLATER BOT %>
		<div class="col col-sm-12 col-lg-4">
			<%= render 'layouts/shared/flater-bot',
					bot_message: "Hey #{current_user.first_name}! Do you know typical rent in this neighbourhood goes from <strong>#{min_rent.to_i}€</strong> to <strong>#{max_rent.to_i}€</strong> per month for a <strong>#{'furnished ' if @flat.furnished}#{@flat.surface.to_i} m²</strong> flat with <strong>#{pluralize(@flat.nb_rooms, 'room')}</strong>?"
			%>
		</div>
	</div>
</div>

app/views/rentals/organize_visit.html.erb
<%# HEADER %>
<%= render 'layouts/shared/dashboard-breadcrumb',
		id: "organize-visit",
		title: "Organize a new visit",
		links: [
			{ text: "My flat ##{@flat.id}", link: flat_path(@flat.id) },
			{ text: "Rental ##{@rental.id}", link: flat_rental_path(@flat.id, @rental.id) },
			{ text: "Organize visit" }
		],
		flat: @flat
%>

<div class="container">
	<div class="row">
		<div class="col col-sm-12 col-lg-8">
			<%# VISIT FORM %>
			<p class="lead">When do you want to <strong>plan the visit</strong>?</p>
			<%= simple_form_for (@task) do |f| %>
				<%= f.error_notification %>
				<%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
				<%= f.input :rental_id, as: :hidden, input_html: { value: @rental.id } %>
				<%= f.input :status, as: :hidden, input_html: { value: 0 } %>
				<%= f.input :action, as: :hidden, input_html: { value: 'Visit' } %>
				<div class="form-row">
					<div class="col-6">
						<%= f.input :date, label: "Date", html5:true, input_html: { value: Date.today, class: "datepicker"} %>
					</div>
					<div class="col-6">
						<%= f.input :time, label: "Schedule" %>
					</div>
				</div>
				<%= f.input :complementary_info, as: :text, label: "Complementary information", input_html: { rows: 5, value: "Hello {first_name}! Your dossier have been selected. I'm please to invite you for a visit the {date} at #{@flat.address}."} %>
				<%= f.button :submit, "Organize Visit", class: "btn-primary" %>
				<%= link_to "‹ Back", flat_rental_path(@flat, @rental), {class: "btn btn-secondary"} %>
			<% end %>
			<br/>
			<%# RECIPIENTS %>
			<p>Following candidates will receive a <strong>message with all information</strong> to visit the flat.</p>
			<ul class="mb-5">
				<% @rental.dossiers.each do |dossier| %>
					<% if dossier.status == "ok_for_visit"%>
						<li>
							<strong>
							<%= "#{dossier.candidate.first_name} #{dossier.candidate.last_name}" %>
							</strong>
							<%= "(#{dossier.candidate.email})" %>
						</li>
					<% end %>
				<% end %>
			</ul>
		</div>
		<%# FLATER BOT %>
		<div class="col col-sm-12 col-lg-4">
			<%= render 'layouts/shared/flater-bot',
					bot_message: "Congrats  #{current_user.first_name.capitalize}! You're planning visits! Don't worry about no show, I'll send <strong>email or sms reminders</strong> 24 hours and 1 hour before the visit!",
					bot_action: "<a href=\"#\">Don't send automatic reminders</a>"
			%>
		</div>
	</div>
</div>

app/views/rentals/select_tenant.html.erb
<%# HEADER %>
<%= render 'layouts/shared/dashboard-breadcrumb',
		title: "You are about to select your new tenant",
		links: [
			{ text: "My flat ##{@flat.id}", link: flat_path(@flat.id) },
			{ text: "Rental ##{@rental.id} (#{@rental.pending ? "pending" : "closed"})" }
		],
		flat: @flat
%>


<div class="container">
	
		<div class="text-center">
		   <p>You have selected <strong><%= @selected_dossier.candidate.first_name %> <%= @selected_dossier.candidate.last_name %> </strong> as your future tenant:</p>
		</div>

		<div class="text-center">
	      <%= cl_image_tag("Faces/#{@selected_dossier.candidate.facebook_picture_url}",:width=>300, :height=>300, :gravity=>"face", :radius=>"max", :crop=>"thumb") %>
	    </div>
		<br>
		<div class="text-center">
	      <i class="fas fa-user-circle text-primary"></i> The candidate will be informed by e-mail.
	      <br>
	      <i class="fas fa-users text-primary"></i> Other candidates will be noticed that they have not been retained.
	      <br><br>
	    </div>

		<div class="text-center">
			<%= link_to "Confirm tenant", confirm_tenant_flat_rental_path(@flat, @rental, dossier_id: @selected_dossier.id), method: :post, class: "btn btn-primary" %>
	    </div>

</div>

app/views/rentals/show.html.erb
<% # VARIABLES
dossier_total = @rental.dossiers.count
dossier_rejected = @rental.dossiers.where(status: 'not_selected').count
dossier_to_improve = @rental.dossiers.where(status: 'to_improve').count
dossier_ok_for_visit = @rental.dossiers.where(status: 'ok_for_visit').count
dossier_visiting = @rental.dossiers.where(status: 'visiting').count
dossier_to_validate = dossier_visiting + dossier_ok_for_visit
is_are = dossier_to_validate > 1 ? 'are' : 'is'
documents = ['latest-revenues', 'tax-notices', 'ID', 'guarantors']
# TODO documents should supply: type of document (title), id (for modal), validation (true or false), document URL / content (for modal)
%>

<%# HEADER %>
<%= render 'layouts/shared/dashboard-breadcrumb',
		title: "#{pluralize(dossier_to_validate, 'applicant')} out of #{dossier_total} #{is_are} selected for visits",
		links: [
			{ text: "My flats", link: flats_path },
			{ text: "My flat ##{@flat.id}", link: flat_path(@flat.id) },
			{ text: "Rental ##{@rental.id} #{badge(@rental.status[:text], @rental.status[:color], @rental.status[:icon], '', false)}" }
		],
		flat: @flat
%>

<div class="container">
	<div class="row">
		<div class="col col-12">
			<div class="card-dashboard">
			<%# RENTAL IS PENDING %>
			<% if @rental.pending %>
				<%# DISPLAY DOSSIERS %>
				<% if dossier_total > 0 %>
				<div>
					<% ["visiting", "ok_for_visit", "to_improve", "not_selected"].each do  |status|%>
						<div id="<%= status %>" >
							<h3 class="d-flex justify-content-between align-items-center pt-3 ">
								<%# TITLE %>
								<div><i class="fas fa-users"></i> <%= "#{@rental.dossiers.where(status: status).count} #{status.gsub('_', ' ')}" %></div>
								<%# CTA: VISITED - CONS-VISIT %>
								<% if status == 'visiting' && @rental.dossiers.where(status: status).count > 0 %>
									<div>
										<%= link_to "Organize another visit", "#", class: 'btn btn-outline-info'  %>
									</div>
								<% end %>
								<%# CTA: OK FOR VISIIT - ORGANIZE VISIT %>
								<% if status == 'ok_for_visit' && @rental.dossiers.where(status: status).count > 0 %>
									<div>
										<%= link_to "Organize visit", organize_visit_flat_rental_path(@flat, @rental), class: 'btn btn-primary'  %>
									</div>
								<% end %>
								<%# CTA: TO IMPROVE - RELAUNCH FOR VALIDATION %>
								<% if status == 'to_improve' && @rental.dossiers.where(status: status).count > 0 %>
									<div>
										<%= link_to "Relaunch for validation", '', class: 'btn btn-warning', data: { toggle: "modal", target: "#relaunch" } %>
									</div>
								<% end %>
							</h3>
							<%# CANDIDATE LIST %>
							<ul class="list-group <%= status %>">
								<%= render 'candidates_list', rental: @rental, status: status, documents: documents %>
							</ul>
						</div>
					<% end %>
				</div>
			</div>

			<%# PROOF MODAL %>
			<% documents.each do |document| %>
				<%= render 'layouts/shared/modal',
						id: "document-#{document}",
						label: document,
						title: "<i class=\"fas fa-file-alt text-primary\"></i> #{document.gsub('-', ' ').capitalize}",
						content: 	cl_image_tag("dossiers/1/tax_proof_gxkwir", crop: :fit, :effect=>"grayscale")
				%>	
			<% end %>
			<%# RELAUNCH MODAL %>
			<%= render 'layouts/shared/modal',
					id: 'relaunch',
					label: 'relaunch',
					title: 'Notifications sent! <i class="fas fa-check text-primary"></i>',
					# content: (render 'layouts/shared/flater-bot',
					# bot_message: "<strong>These #{pluralize(dossier_to_improve, 'candidate')} have been sent a notification</strong> with individual flaw details in order they complete their dossier. Hope they're going eligible to visit soon!")
					content: "<strong>These 3 candidates have been sent a notification</strong> with individual flaw details in order they complete their dossier.</p><p>Hope they're going eligible to visit soon!</p>"
			%>	

		<% end %>
		<%# RENTAL IS CLOSED %>
		<% else %>
			<div>
				<%=  "Tenant ##{@rental.tenant_id} has been selected for this rental"%>
				<%=  " - Associated dossier ##{@rental.dossiers.where(candidate_id: @rental.tenant_id).last.id} - " %>
				<%= link_to "Generate contract", "#"  %>

			</div>
		<% end %>
		</div>
	</div>
</div>